apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-storage

commonAnnotations:
  argocd.argoproj.io/sync-wave: "8"

resources:
  - cephobjectstore.yaml
  - ocsinitialization.yaml
  - rook-ceph-rgw-route.yaml
  - rook-ceph-rgw-service.yaml
