apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../manifests/operators/amq-streams
- ../../../manifests/operators/odh/overlays/beta
- ../../../manifests/operators/pipelines/
- ../../../manifests/operators/serverless/overlays/4.5