apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
spec:
  dex:
    openShiftOAuth: true
  server:
    autoscale:
      enabled: true
    route:
      enabled: true
  statusBadgeEnabled: true
  rbac:
    policy: |
      g, system:cluster-admins:admin