apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: knative-serving

commonAnnotations:
  argocd.argoproj.io/sync-wave: "5"

resources:
  - knative-serving-instance.yaml
  - knative-serving-namespace.yaml
