apiVersion: noobaa.io/v1alpha1
kind: BackingStore
metadata:
  name: noobaa-default-backing-store
  finalizers:
    - noobaa.io/finalizer
  labels:
    app: noobaa
spec:
  awsS3:
    region: ap-southeast-1
    secret:
      name: noobaa-aws-cloud-creds-secret
      namespace: openshift-storage
    targetBucket: nb.1611685472104.apps.cluster-0183.0183.example.opentlc.com
  type: aws-s3
