apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: knative-eventing

commonAnnotations:
  argocd.argoproj.io/sync-wave: "3"

resources:
  - knative-eventing-instance.yaml
#  - knative-eventing-namespace.yaml
