apiVersion: noobaa.io/v1alpha1
kind: BucketClass
metadata:
  name: noobaa-default-bucket-class
  finalizers:
    - noobaa.io/finalizer
  labels:
    app: noobaa
spec:
  placementPolicy:
    tiers:
      - backingStores:
          - noobaa-default-backing-store
