apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "5"

bases:
- ../../../manifests/operator-instances/openshift-container-storage-noobaa
- ../../../manifests/operator-instances/openshift-container-rgw
- ../../../manifests/operator-instances/openshift-serverless-knative-eventing/overlays/knative-kafka
- ../../../manifests/operator-instances/openshift-serverless-knative-serving/overlays/default
