apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

resources:
  - knative-kafka-instance.yaml

patchesJson6902:
- target:
    group: operators.coreos.com
    version: v1alpha1
    kind: Subscription
    name: serverless-operator
    namespace: openshift-operators
  path: patch-channel-and-version.yaml