apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-storage

bases:
  - github.com/redhat-canada-gitops/catalog/openshift-container-storage-noobaa/overlays/default?ref=master
