apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kogito-operator
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: kogito-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: kogito-operator.v1.1.0
