apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-operators

bases:
  - github.com/redhat-canada-gitops/catalog/openshift-pipelines-operator/overlays/stable?ref=master
