apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-storage

commonAnnotations:
  argocd.argoproj.io/sync-wave: "3"

bases:
  - ./openshift-container-storage-node-labeler

resources:
  - storagecluster.yaml
