apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-operators

bases:
  - github.com/redhat-canada-gitops/catalog/openshift-container-storage-operator/overlays/stable-4.6?ref=master
