apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: 'true'
  name: global-operators
  namespace: openshift-operators
spec: {}